name: soratun

on:
  workflow_dispatch:

jobs:
  run-soratun:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: download soratun
        run: |
          wget https://github.com/soracom/soratun/releases/download/v1.2.7/soratun_1.2.7_linux_amd64.tar.gz
          tar xvfz soratun_1.2.7_linux_amd64.tar.gz
          cp soratun_1.2.7_linux_amd64/soratun /usr/local/bin/
      - name: create arc.json
        run: |
          soratun config > arc.json
          cat arc.json
