name: soratun

on:
  push:
  workflow_dispatch:

jobs:
  run-soratun:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: node:18
      options: --privileged
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: download soratun
        run: |
          apt -y update
          apt -y install jq
          apt -y install iputils-ping net-tools
          curl -OL https://github.com/soracom/soratun/releases/download/v1.2.7/soratun_1.2.7_linux_amd64.tar.gz
          tar xvfz soratun_1.2.7_linux_amd64.tar.gz
          cp soratun_1.2.7_linux_amd64/soratun /usr/local/bin/
      - name: create arc.json
        run: |
          soratun config > arc.json
          cat arc.json | jq ".privateKey = \"$private_key\" | .publicKey = \"$client_peer_public_key\" | .simId = \"$simid\" | .arcSessionStatus.arcServerPeerPublicKey = \"$public_key\" | .arcSessionStatus.arcServerEndpoint = \"$endpoint\" | .arcSessionStatus.arcAllowedIPs = $allowed_ips" > soratun.json
          cat soratun.json
        env:
          simid: ${{ secrets.ARC_SIMID }}
          private_key : ${{ secrets.ARC_PRIVATE_KEY }}
          public_key : ${{ secrets.ARC_PUBLIC_KEY }}
          endpoint : ${{ secrets.ARC_ENDPOINT }}
          allowed_ips : ${{ vars.ARC_ALLOWED_IPS }}
          client_peer_public_key : ${{ secrets.ARC_CLIENT_PEER_PUBLIC_KEY }}
      - name: soratun up
        run: soratun up --config soratun.json &
      - name: ping
        run: ping -c 3 100.127.100.127
